# Generated by Django 5.1.2 on 2024-10-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
